# Generated by Django 4.1 on 2024-05-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_solicitud_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='publicacionOfrecida',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, related_name='ofrecimientos', to='core.publicacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.publicacion'),
        ),
    ]
