<<<<<<< HEAD
# Generated by Django 4.1 on 2024-04-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_contraseña_alter_usuario_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failedloginattempt',
            old_name='username',
            new_name='email',
        ),
    ]
=======
# Generated by Django 4.1 on 2024-04-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_contraseña_alter_usuario_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failedloginattempt',
            old_name='username',
            new_name='email',
        ),
    ]
>>>>>>> origin/nuevo
