# Generated by Django 4.1 on 2024-05-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_categoria_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntuacion',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
    ]
