# Generated by Django 4.1 on 2024-05-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_solicitud_estado_solicitud_publicacionofrecida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
