# Generated by Django 5.0.4 on 2024-06-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donation_solicitud_rechazado_busquedafavorita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='monto',
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(default='unknown_payment_id', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='user_id',
            field=models.CharField(default='unknown_user_id', max_length=50),
        ),
    ]
