# Generated by Django 5.0.4 on 2024-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_date_donation_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date_created',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
