# Generated by Django 5.0.4 on 2024-06-27 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_date_created_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
