# Generated by Django 5.0.4 on 2024-06-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='preference_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
