# Generated by Django 5.0.4 on 2024-05-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_publicacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='filial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
