# Generated by Django 5.0.4 on 2024-05-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_publicacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estadoCategoria',
            field=models.BooleanField(default=True),
        ),
    ]
