# Generated by Django 5.0.4 on 2024-06-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usuario_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
    ]
