# Generated by Django 5.0.4 on 2024-05-27 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='ayudante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
