# Generated by Django 4.1 on 2024-05-26 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
