# Generated by Django 5.0.4 on 2024-05-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_trueque_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueque',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
