# Generated by Django 5.0.4 on 2024-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_publicacion_trueque'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='rechazado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='trueque',
            field=models.BooleanField(default=True),
        ),
    ]
