# Generated by Django 5.0.4 on 2024-06-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_solicitud_rechazado_alter_publicacion_trueque'),
        ('core', '0025_publicacion_eliminada'),
    ]

    operations = [
    ]
