# Generated by Django 5.0.4 on 2024-06-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20240605_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='filial',
            new_name='filial_nombre',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='eliminada',
        ),
    ]
