# Generated by Django 5.0.4 on 2024-06-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_filial_ayudante'),
        ('core', '0027_rename_filial_usuario_filial_nombre_and_more'),
    ]

    operations = [
    ]
