# Generated by Django 5.0.4 on 2024-06-05 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20240605_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categoria',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='trueque',
            field=models.BooleanField(default=False),
        ),
    ]
