# Generated by Django 4.1 on 2024-06-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_solicitud_trueque_busquedafavorita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='rechazado',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='trueque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.trueque'),
        ),
        migrations.DeleteModel(
            name='BusquedaFavorita',
        ),
    ]
