# Generated by Django 4.1 on 2024-06-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_solicitud_rechazado_solicitud_trueque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
