# Generated by Django 5.0.4 on 2024-06-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_publicacion_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
