# Generated by Django 5.0.4 on 2024-06-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_publicacion_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueque',
            name='estado',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('penalizado', 'Penalizado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10),
        ),
    ]
