# Generated by Django 5.0.4 on 2024-06-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_trueque_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
