# Generated by Django 5.0.4 on 2024-06-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_categoria_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
