# Generated by Django 4.1 on 2024-06-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_trueque_estado_usuario_fecha_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='stock',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='core.solicitud'),
        ),
    ]
