# Generated by Django 5.0.4 on 2024-06-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_canje'),
    ]

    operations = [
        migrations.AddField(
            model_name='canje',
            name='codigo_retiro',
            field=models.CharField(default='', max_length=20),
        ),
    ]
