# Generated by Django 5.0.4 on 2024-06-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_publicacion_stock_alter_valoracion_solicitud'),
        ('core', '0037_canje_codigo_retiro'),
    ]

    operations = [
    ]
